name: Build and Upload ESP8266 Firmware

on:
  push:
    branches:
      - '**'  # 匹配所有分支
  pull_request:
    branches:
      - '**'  # 匹配所有分支的拉取请求

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检查代码库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 克隆子模块（如MavLink）

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 安装PlatformIO
      - name: Install PlatformIO
        run: |
          pip install --user platformio
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 获取所有PlatformIO环境
      - name: Get PlatformIO Environments
        id: get_envs
        run: |
          envs=$(platformio project config --get env | grep -o '\[env:.*\]' | sed 's/\[env://;s/\]//')
          echo "environments=$envs" >> $GITHUB_OUTPUT

      # 运行PlatformIO编译所有目标
      - name: Build All Firmware
        run: |
          platformio run

      # 上传所有环境的固件文件作为产物
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp8266-firmware
          path: |
            .pio/build/*/*.bin
          retention-days: 7
